

/*----------------Top 10 Occupations----------------------------------*/

SELECT SOC_NAME AS TOP_OCCUPATIONS, NUMBER_CERTIFIED_APPLICATIONS, PERCENTAGE
FROM(
SELECT SOC_CODE,SOC_NAME,NUMBER_CERTIFIED_APPLICATIONS,TRIM(TO_CHAR(ROUND((NUMBER_CERTIFIED_APPLICATIONS/TOTAL_CERTIFIED)*100,1),999999999.9))||'%' AS PERCENTAGE
FROM(
SELECT SOC_CODE,MAX(SOC_NAME) AS SOC_NAME,COUNT(*) AS NUMBER_CERTIFIED_APPLICATIONS,
      (SELECT COUNT(*) FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED') AS TOTAL_CERTIFIED
FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED'
GROUP BY SOC_CODE
) T ORDER BY NUMBER_CERTIFIED_APPLICATIONS desc, SOC_NAME asc) WHERE ROWNUM <= 10;


/*----------------Top 10 States----------------------------------*/

SELECT STATE AS TOP_STATES, NUMBER_CERTIFIED_APPLICATIONS, PERCENTAGE
FROM(
SELECT STATE,NUMBER_CERTIFIED_APPLICATIONS,TRIM(TO_CHAR(ROUND((NUMBER_CERTIFIED_APPLICATIONS/TOTAL_CERTIFIED)*100,1),999999999.9))||'%' AS PERCENTAGE
FROM(
SELECT STATE,COUNT(*) AS NUMBER_CERTIFIED_APPLICATIONS,
      (SELECT COUNT(*) FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED') AS TOTAL_CERTIFIED
FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED'
GROUP BY STATE
) T ORDER BY NUMBER_CERTIFIED_APPLICATIONS desc, STATE asc) WHERE ROWNUM <= 10;