

/*----------------Top 10 Occupations----------------------------------*/

SELECT SOC_NAME AS TOP_OCCUPATIONS, NUMBER_CERTIFIED_APPLICATIONS, PERCENTAGE
FROM(
SELECT SOC_CODE,SOC_NAME,NUMBER_CERTIFIED_APPLICATIONS,TRIM(TO_CHAR(ROUND((NUMBER_CERTIFIED_APPLICATIONS/TOTAL_CERTIFIED)*100,1),999999999.9))||'%' AS PERCENTAGE
FROM(
SELECT H.SOC_CODE,C.SOC_NAME,COUNT(*) AS NUMBER_CERTIFIED_APPLICATIONS,
      (SELECT COUNT(*) FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED') AS TOTAL_CERTIFIED
FROM H1B_STATUS H INNER JOIN (SELECT SOC_CODE, SOC_NAME
                              FROM(
                              SELECT SOC_CODE, SOC_NAME, RANK() OVER (PARTITION BY SOC_CODE ORDER BY ROWID desc) AS RN 
                              FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED') WHERE RN=1) C ON H.SOC_CODE=C.SOC_CODE
WHERE UPPER(H.STATUS)='CERTIFIED'
GROUP BY H.SOC_CODE,C.SOC_NAME
) T ORDER BY NUMBER_CERTIFIED_APPLICATIONS desc, SOC_NAME asc) WHERE ROWNUM <= 10;


/*----------------Top 10 States----------------------------------*/

SELECT STATE AS TOP_STATES, NUMBER_CERTIFIED_APPLICATIONS, PERCENTAGE
FROM(
SELECT STATE,NUMBER_CERTIFIED_APPLICATIONS,TRIM(TO_CHAR(ROUND((NUMBER_CERTIFIED_APPLICATIONS/TOTAL_CERTIFIED)*100,1),999999999.9))||'%' AS PERCENTAGE
FROM(
SELECT STATE,COUNT(*) AS NUMBER_CERTIFIED_APPLICATIONS,
      (SELECT COUNT(*) FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED') AS TOTAL_CERTIFIED
FROM H1B_STATUS WHERE UPPER(STATUS)='CERTIFIED'
GROUP BY STATE
) T ORDER BY NUMBER_CERTIFIED_APPLICATIONS desc, STATE asc) WHERE ROWNUM <= 10;